/*
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
