/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.ui;

import de.htwdd.sf.beleg.ui.AbstractMyDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDslUiModule extends AbstractMyDslUiModule {
  public MyDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
