/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.ui.contentassist;

import de.htwdd.sf.beleg.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
