/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.web;

import com.google.inject.Provider;
import de.htwdd.sf.beleg.web.AbstractMyDslWebModule;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDslWebModule extends AbstractMyDslWebModule {
  public MyDslWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
