/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.tests;

import com.google.inject.Inject;
import de.htwdd.sf.beleg.tests.MyDslInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(MyDslInjectorProvider.class)
@SuppressWarnings("all")
public class MyDslParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field MyDslParsingTest.parseHelper refers to the missing type Model");
  }
}
